### PR TITLE
Merge branch '1.3' of ezsystems/ezplatform-rest into 4.1

### PR DESCRIPTION
**Pull request by ezrobot**
Cross merge PR

### CODE REVIEW

**Review by ViniTou — APPROVED** [review]

**Comment by Steveb-p** [comment]
@glye unit & integration tests we're not being run. Added [ff41543](https://github.com/ibexa/rest/pull/35/commits/ff41543bcb3b590a71b46b59edd1870190a7d840) to remedy this.

Calling @mnocon because you were adding it. Do you remember any other instances where version was added like this? Cause for those repositories tests will not launch either in such cases.

**Review by Steveb-p — APPROVED** [review]

**Comment by glye** [comment]
BTW, increasing test timeout in https://github.com/ezsystems/ezplatform-rest/pull/96

**Review by konradoboza — APPROVED** [review]

**Review by alongosz — APPROVED** [review]

**Comment by Steveb-p** [comment]
I think @ezrobot was supposed to add incoming commits into PR's, but does not do so.

The recently added timeout fix needs to be added manually.

**Comment by glye** [comment]
Thanks, seems we're good to merge.

**Comment by ViniTou** [comment]
@glye 
I have merged it up
https://github.com/ibexa/rest/commit/10fc2f2929d85fa78fb274d7474a87c0404cab0c

**Comment by mnocon** [comment]
> Calling @mnocon because you were adding it. Do you remember any other instances where version was added like this? Cause for those repositories tests will not launch either in such cases.

I've checked all usages of `uses: .` in our packages and this was the only one. Thanks for taking care of it!

**Pull request merged**
