### PR TITLE
Added translation configuration

### PR DESCRIPTION
**Pull request by mikadamczyk**
| Question           | Answer
| ------------------ | ------------------
| **JIRA issue**     | N/A
| **Type**| improvement
| **Target version** | Ibexa `v4.5`
| **BC breaks**      | no
| **Tests pass**     | yes
| **Doc needed**     | no
| **Needs**     | https://github.com/ibexa/core/pull/237

**TODO**:
- [ ] Implement tests.
- [x] Fix new code according to Coding Standards (`$ composer fix-cs`).
- [x] Ask for Code Review.

### CODE REVIEW

**Review by adamwojs — APPROVED** [review]
+1 besides code style issues

**Review by alongosz — APPROVED** [review]
Friendly reminder: CS is failing ;)

**Review by konradoboza — APPROVED** [review]
In case you forget: CS is failing. 😜

**Review by ViniTou — APPROVED** [review]
Seems there are some code style issues, other than that LGTM

**Pull request merged**
